name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install Dependencies
        run: npm install

      - name: Configure Git Identity
        run: |
          git config --global user.email "abhijaychaudhary8@gmail.com"
          git config --global user.name "abhijeet singh"

      - name: Deploy Application
        run: npm run deploy
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GH_TOKEN_USERNAME: ${{ secrets.GH_TOKEN }}
          GH_TOKEN_PASSWORD: ${{ secrets.GH_TOKEN }}


      - name: List Directory Contents
        run: ls -la

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.email "abhijaychaudhary8@gmail.com"
          git config --global user.name "Abhijeet Singh"
          git checkout --orphan gh-pages
          git rm -rf .
          mv dist/* .
          rm -r dist
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push origin gh-pages --force
        env:
          CI: true

