name: Deploy

on:
  push:
    branches:
      - master  # Update to match your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install npm dependencies
        run: npm i

      - name: Build
        run: npm run build

      - name: Configure Git
        run: |
          git config --global user.email "abhijaychaudhary8@gmil.com"
          git config --global user.name "abhijeetpoonia"

      - name: Deploy
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}  # Create a GitHub secret called NPM_TOKEN with your npm authentication token
        run: |
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
          npm run deploy

